{% set name = "bumps" %}
{% set version = "0.7.16" %}
{% set sha256 = "3594452487b8404f1efaace9b70aefaeb345fa44dd74349f7829a61161d2f69a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - scripts.patch # use entry points instead of installing scripts

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - bumps = bumps.cli:main

requirements:
  host:
    - python
    - pip
    - six
  run:
    - python
    - numpy
    - scipy
    - six

test:
  imports:
    - bumps
    - bumps.dream
    - bumps.gui
    - bumps.mystic
    - bumps.mystic.examples
    - bumps.mystic.optimizer
    - bumps.numdifftools

about:
  home: http://www.reflectometry.org/danse/software.html
  license: PUBLIC-DOMAIN
  license_file: LICENSE.txt
  summary: Data fitting with bayesian uncertainty analysis
  doc_url: https://bumps.readthedocs.io
  dev_url: https://github.com/bumps/bumps
